/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/cellphone.glb -K -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cellphone.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh name="MobilePhone_Phone_Alpha_0" geometry={nodes.MobilePhone_Phone_Alpha_0.geometry} material={materials.Phone_Alpha} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="MobilePhone_Phone_Main_0" geometry={nodes.MobilePhone_Phone_Main_0.geometry} material={materials.Phone_Main} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Screen" geometry={nodes.Screen.geometry} material={materials.e} position={[0, 0, 0.007]} rotation={[Math.PI / 2, 0, 3.108]} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/cellphone.glb')
