/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/ipad.glb -K -k 
Author: DatSketch (https://sketchfab.com/DatSketch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ipad-mini-6-2021-f363c2b1c74a462588db184bd4fb024e
Title: IPad Mini 6 2021
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ipad.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <mesh name="iPad_Mini_BaseColor_0" geometry={nodes.iPad_Mini_BaseColor_0.geometry} material={materials.PaletteMaterial001} position={[0, 0.033, -0.012]} />
        <mesh name="iPad_Mini_SpeakerMic_0" geometry={nodes.iPad_Mini_SpeakerMic_0.geometry} material={materials.SpeakerMic} position={[0, 0.033, -0.012]} />
        <mesh name="iPad_Mini_CamGlass_0" geometry={nodes.iPad_Mini_CamGlass_0.geometry} material={materials.PaletteMaterial002} position={[0, 0.033, -0.012]} />
        <mesh name="iPad_Mini_Screen_0" geometry={nodes.iPad_Mini_Screen_0.geometry} material={materials.Screen} position={[0, 0.033, -0.012]} />
        <mesh name="iPad_Mini_Lens_0" geometry={nodes.iPad_Mini_Lens_0.geometry} material={materials.Lens} position={[0, 0.033, -0.012]} />
      </group>
    </group>
  )
}

useGLTF.preload('/ipad.glb')
