/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/ipad.glb -K -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {

  useVideoTexture
} from "@react-three/drei";
export function Ipad(props) {
  
  const { nodes, materials } = useGLTF('models/ipad.glb')
  const textureCel2 = useVideoTexture("textures/ipad2.mp4",{loop:true})
  return (

<group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <mesh castShadow receiveShadow name="iPad_Mini_BaseColor_0" geometry={nodes.iPad_Mini_BaseColor_0.geometry} material={materials.PaletteMaterial001} position={[0, 0.033, -0.012]} />
        <mesh castShadow receiveShadow name="iPad_Mini_SpeakerMic_0" geometry={nodes.iPad_Mini_SpeakerMic_0.geometry} material={materials.SpeakerMic} position={[0, 0.033, -0.012]} />
        <mesh castShadow receiveShadow name="iPad_Mini_CamGlass_0" geometry={nodes.iPad_Mini_CamGlass_0.geometry} material={materials.PaletteMaterial002} position={[0, 0.033, -0.012]} />
        <mesh castShadow receiveShadow 
        name="iPad_Mini_Screen_0" 
        geometry={nodes.iPad_Mini_Screen_0.geometry} 
        material={materials.Screen} 
        position={[.01, 0.023, -0.017]} 
        scale={[1.5, .67, 1]}
        rotation={[0, 0, -1.57]}>
        <meshBasicMaterial map={textureCel2} toneMapped={true} forceSinglePass={true}/>
          </mesh>
        <mesh castShadow receiveShadow name="iPad_Mini_Lens_0" geometry={nodes.iPad_Mini_Lens_0.geometry} material={materials.Lens} position={[0, 0.033, -0.012]} />
      </group>
    </group>
    
    

  

  )
}

useGLTF.preload('models/ipad.glb')
