/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/ipad.glb -K -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {

  useVideoTexture
} from "@react-three/drei";
export function IpadTwo(props) {
  
  const { nodes, materials } = useGLTF('models/ipad.glb')
  const textureCel3 = useVideoTexture("textures/ipad3.mp4",{loop:true})
  return (

<group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <mesh castShadow receiveShadow name="iPad_Mini_BaseColor_0" geometry={nodes.iPad_Mini_BaseColor_0.geometry} material={materials.PaletteMaterial001} position={[0, 0.033, -0.012]} />
        <mesh castShadow receiveShadow name="iPad_Mini_SpeakerMic_0" geometry={nodes.iPad_Mini_SpeakerMic_0.geometry} material={materials.SpeakerMic} position={[0, 0.033, -0.012]} />
        <mesh castShadow receiveShadow name="iPad_Mini_CamGlass_0" geometry={nodes.iPad_Mini_CamGlass_0.geometry} material={materials.PaletteMaterial002} position={[0, 0.033, -0.012]} />
        <mesh castShadow receiveShadow 
        name="iPad_Mini_Screen_0" 
        geometry={nodes.iPad_Mini_Screen_0.geometry} 
        material={materials.Screen} 
        position={[.001, 0.039, -0.017]} 
        scale={[1, 1, 1]}
        rotation={[0, 0, 0]}>
        <meshBasicMaterial map={textureCel3} toneMapped={true} forceSinglePass={true}/>
          </mesh>
        <mesh castShadow receiveShadow name="iPad_Mini_Lens_0" geometry={nodes.iPad_Mini_Lens_0.geometry} material={materials.Lens} position={[0, 0.033, -0.012]} />
      </group>
    </group>
    
    

  

  )
}

useGLTF.preload('models/ipad.glb')
