/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/office.glb -K -k 
*/

import React, { useRef } from 'react'
import { useGLTF, useVideoTexture,Float } from '@react-three/drei'
import { motion } from 'framer-motion-3d';

export function Office(props) {
  const {section} = props;
  const { nodes, materials } = useGLTF('models/office.glb')
  const textureVSCode = useVideoTexture("textures/vscode.mp4")
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="bike" position={[-1.367, -0.421, 0.939]} rotation={[-1.6, -0.22, 3.07]} scale={0.284}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Bicycle_29" position={[-0.108, -0.024, 0.325]} rotation={[-0.011, 0.05, 0]} scale={1.055}>
                <group name="Back_brake_cable_0" position={[-0.604, 3.138, 1.342]} scale={1.492}>
                  <mesh  castShadow receiveShadow name="Object_6" geometry={nodes.Object_6.geometry} material={materials.Steering} />
                </group>
                <group name="Circle002_3" position={[0, 1.119, -1.7]} scale={1.492}>
                  <mesh  castShadow receiveShadow name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Tires} />
                  <mesh  castShadow receiveShadow name="Object_12" geometry={nodes.Object_12.geometry} material={materials['Material.001']} />
                </group>
                <group name="Circle004_5" position={[-0.137, 0.878, -0.404]} rotation={[0, 0, -Math.PI / 2]} scale={1.492}>
                  <mesh  castShadow receiveShadow name="Object_14" geometry={nodes.Object_14.geometry} material={materials.Metal} />
                </group>
                <group name="Circle005_6" position={[-0.132, 0.878, -0.404]} rotation={[0, 0, -Math.PI / 2]} scale={1.492}>
                  <mesh  castShadow receiveShadow name="Object_16" geometry={nodes.Object_16.geometry} material={materials.Metal} />
                </group>
                <group name="Circle006_7" position={[-0.137, 1.119, -1.7]} rotation={[0, 0, -Math.PI / 2]} scale={0.803}>
                  <mesh  castShadow receiveShadow name="Object_18" geometry={nodes.Object_18.geometry} material={materials.Metal} />
                </group>
                <group name="Circle007_8" position={[0, 1.119, 1.441]} rotation={[-Math.PI, 0, 0]} scale={-1.492}>
                  <mesh  castShadow receiveShadow name="Object_20" geometry={nodes.Object_20.geometry} material={materials.Metal} />
                </group>
                <group name="Circle008_9" position={[0, 1.119, -1.7]} rotation={[-Math.PI, 0, 0]} scale={-1.492}>
                  <mesh  castShadow receiveShadow name="Object_22" geometry={nodes.Object_22.geometry} material={materials.Metal} />
                </group>
                <group name="Circle_1" position={[0, 1.119, 1.441]} scale={1.492}>
                  <mesh  castShadow receiveShadow name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Tires} />
                  <mesh  castShadow receiveShadow name="Object_9" geometry={nodes.Object_9.geometry} material={materials['Material.001']} />
                </group>
                <group name="Cylinder001_11" position={[0, 1.119, -1.7]} scale={[1.162, 1.492, 1.492]}>
                  <mesh  castShadow receiveShadow name="Object_26" geometry={nodes.Object_26.geometry} material={materials.Metal} />
                </group>
                <group name="Cylinder002_12" position={[0, 0.878, -0.404]} rotation={[0, 0, -Math.PI / 2]} scale={[1.546, 1.927, 1.546]}>
                  <mesh  castShadow receiveShadow name="Object_28" geometry={nodes.Object_28.geometry} material={materials.Metal_orange} />
                </group>
                <group name="Cylinder003_13" position={[0, 0.878, -0.404]} rotation={[0.239, 0, -Math.PI / 2]} scale={1.546}>
                  <mesh  castShadow receiveShadow name="Object_30" geometry={nodes.Object_30.geometry} material={materials.Metal} />
                </group>
                <group name="Cylinder004_14" position={[0, 0.878, -0.404]} rotation={[0.239, 0, -Math.PI / 2]} scale={-1.546}>
                  <mesh  castShadow receiveShadow name="Object_32" geometry={nodes.Object_32.geometry} material={materials.Metal} />
                </group>
                <group name="Cylinder005_15" position={[0, 3.096, 1.4]} rotation={[-0.878, 0, 0]} scale={0.157}>
                  <mesh  castShadow receiveShadow name="Object_34" geometry={nodes.Object_34.geometry} material={materials.Steering} />
                </group>
                <group name="Cylinder_10" position={[0, 1.119, 1.441]} rotation={[0, 0, -Math.PI / 2]} scale={0.12}>
                  <mesh  castShadow receiveShadow name="Object_24" geometry={nodes.Object_24.geometry} material={materials.Metal} />
                </group>
                <group name="Front_brake_cable001_17" position={[0.604, 3.138, 1.342]} scale={1.492}>
                  <mesh  castShadow receiveShadow name="Object_36" geometry={nodes.Object_36.geometry} material={materials.Steering} />
                </group>
                <group name="Plane001_19" position={[0, 3.02, 1.387]} rotation={[0, 0, -Math.PI / 2]} scale={1.492}>
                  <mesh  castShadow receiveShadow name="Object_40" geometry={nodes.Object_40.geometry} material={materials.Metal} />
                </group>
                <group name="Plane002_20" position={[0, 2.135, 1.064]} rotation={[1.27, 0, 0]} scale={1.492}>
                  <mesh  castShadow receiveShadow name="Object_42" geometry={nodes.Object_42.geometry} material={materials.Metal} />
                </group>
                <group name="Plane003_21" position={[0, 2.117, -1.24]} rotation={[2.169, 0, 0]} scale={1.492}>
                  <mesh  castShadow receiveShadow name="Object_44" geometry={nodes.Object_44.geometry} material={materials.Metal} />
                </group>
                <group name="Plane004_22" position={[0, 2.218, -1.135]} rotation={[-1.001, 0, 0]} scale={[0.129, 0.319, 0.129]}>
                  <mesh  castShadow receiveShadow name="Object_46" geometry={nodes.Object_46.geometry} material={materials.Metal} />
                </group>
                <group name="Plane005_23" position={[0, 2.281, 0.989]} rotation={[-1.873, 0, 0]} scale={[0.129, 0.319, 0.129]}>
                  <mesh  castShadow receiveShadow name="Object_48" geometry={nodes.Object_48.geometry} material={materials.Metal} />
                </group>
                <group name="Plane_18" position={[0, 2.951, -0.96]} scale={0.151}>
                  <mesh  castShadow receiveShadow name="Object_38" geometry={nodes.Object_38.geometry} material={materials.Seat} />
                </group>
                <group name="Vert001_24" scale={1.492}>
                  <mesh  castShadow receiveShadow name="Object_50" geometry={nodes.Object_50.geometry} material={materials.Metal_orange} />
                </group>
                <group name="Vert003_26" position={[0, 2.691, 0.79]} scale={1.492}>
                  <mesh  castShadow receiveShadow name="Object_52" geometry={nodes.Object_52.geometry} material={materials.Steering} />
                </group>
                <group name="Vert004_27" position={[0, 2.666, -0.881]} scale={1.492}>
                  <mesh  castShadow receiveShadow name="Object_54" geometry={nodes.Object_54.geometry} material={materials.Metal} />
                </group>
                <group name="Vert005_28" position={[0, 2.691, 0.79]} scale={1.492}>
                  <mesh  castShadow receiveShadow name="Object_56" geometry={nodes.Object_56.geometry} material={materials.Metal} />
                </group>
                <mesh  castShadow receiveShadow name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Metal_orange} />
              </group>
            </group>
          </group>
        </group>
        <mesh  castShadow receiveShadow name="shoe" geometry={nodes.shoe.geometry} material={materials.material0} position={[1.512, -0.163, 0.924]} rotation={[-0.731, 0.121, -0.347]} scale={0.327} />
        <group name="pencil" position={[-0.526, -0.355, 0.777]} rotation={[0, 0.536, 0]} scale={0.258}>
          <mesh  castShadow receiveShadow name="Circle004_Circle008_1" geometry={nodes.Circle004_Circle008_1.geometry} material={materials.FF9800} />
          <mesh  castShadow receiveShadow name="Circle004_Circle008_1_1" geometry={nodes.Circle004_Circle008_1_1.geometry} material={materials.F06292} />
          <mesh  castShadow receiveShadow name="Circle004_Circle008_1_2" geometry={nodes.Circle004_Circle008_1_2.geometry} material={materials['455A64']} />
          <mesh  castShadow receiveShadow name="Circle004_Circle008_1_3" geometry={nodes.Circle004_Circle008_1_3.geometry} material={materials.DD9944} />
          <mesh  castShadow receiveShadow name="Circle004_Circle008_1_4" geometry={nodes.Circle004_Circle008_1_4.geometry} material={materials['1A1A1A']} />
        </group>
        <group name="compu" position={[0.395, -0.312, 0.142]} rotation={[0, 0.528, 0]} scale={0.673}>
          <mesh  castShadow receiveShadow name="mesh256948792" geometry={nodes.mesh256948792.geometry} material={materials['mat16.001']} />
          <mesh  castShadow receiveShadow name="mesh256948792_1" geometry={nodes.mesh256948792_1.geometry} material={materials['mat23.001']} />
          <mesh  castShadow receiveShadow name="mesh256948792_2" geometry={nodes.mesh256948792_2.geometry} material={materials['mat17.001']} />
          <mesh  castShadow receiveShadow name="mesh256948792_3" geometry={nodes.mesh256948792_3.geometry} material={materials.mat25} />
          <group name="group485226736">
            <mesh  castShadow receiveShadow name="mesh485226736" geometry={nodes.mesh485226736.geometry} material={materials['mat16.001']} />
            <mesh  castShadow receiveShadow name="mesh485226736_1" geometry={nodes.mesh485226736_1.geometry} material={materials['mat23.001']} />
            <mesh  castShadow receiveShadow name="mesh485226736_2" geometry={nodes.mesh485226736_2.geometry} material={materials['mat17.001']} />
            <mesh  castShadow receiveShadow name="mesh485226736_3" geometry={nodes.mesh485226736_3.geometry} material={materials['mat15.001']} />
          </group>
        </group>
        <group name="Soccer" position={[-0.557, -0.201, 1.508]} scale={0.361}>
          <mesh  castShadow receiveShadow name="Icosphere_Icosphere006-Mesh" geometry={nodes['Icosphere_Icosphere006-Mesh'].geometry} material={materials.white} />
          <mesh  castShadow receiveShadow name="Icosphere_Icosphere006-Mesh_1" geometry={nodes['Icosphere_Icosphere006-Mesh_1'].geometry} material={materials.black} />
        </group>
        <mesh  castShadow receiveShadow name="route" geometry={nodes.route.geometry} material={materials.fence_columns} position={[-1.271, -0.303, 0.882]} rotation={[0, 1.564, 0]} scale={0.037}>
          <mesh  castShadow receiveShadow name="polySurface1269_ground_0" geometry={nodes.polySurface1269_ground_0.geometry} material={materials.ground} />
          <mesh  castShadow receiveShadow name="polySurface1269_road_0" geometry={nodes.polySurface1269_road_0.geometry} material={materials.road} />
          <mesh  castShadow receiveShadow name="polySurface1279_road_line_0" geometry={nodes.polySurface1279_road_line_0.geometry} material={materials.road_line} />
          <mesh  castShadow receiveShadow name="polySurface1280_fence_0" geometry={nodes.polySurface1280_fence_0.geometry} material={materials.fence} />
          <mesh  castShadow receiveShadow name="polySurface1281_fence_0" geometry={nodes.polySurface1281_fence_0.geometry} material={materials.fence} />
          <mesh  castShadow receiveShadow name="polySurface1281_fence_yello_0" geometry={nodes.polySurface1281_fence_yello_0.geometry} material={materials.fence_yello} />
          <mesh  castShadow receiveShadow name="polySurface1282_fence_columns_0" geometry={nodes.polySurface1282_fence_columns_0.geometry} material={materials.fence_columns} />
          <mesh  castShadow receiveShadow name="polySurface1283_fence_columns_0" geometry={nodes.polySurface1283_fence_columns_0.geometry} material={materials.fence_columns} />
          <mesh  castShadow receiveShadow name="polySurface1284_fence_0" geometry={nodes.polySurface1284_fence_0.geometry} material={materials.fence} />
          <mesh  castShadow receiveShadow name="polySurface1284_fence_yello_0" geometry={nodes.polySurface1284_fence_yello_0.geometry} material={materials.fence_yello} />
          <mesh  castShadow receiveShadow name="polySurface1285_fence_columns_0" geometry={nodes.polySurface1285_fence_columns_0.geometry} material={materials.fence_columns} />
          <mesh  castShadow receiveShadow name="polySurface1286_fence_0" geometry={nodes.polySurface1286_fence_0.geometry} material={materials.fence} />
          <mesh  castShadow receiveShadow name="polySurface1287_fence_0" geometry={nodes.polySurface1287_fence_0.geometry} material={materials.fence} />
          <mesh  castShadow receiveShadow name="polySurface1287_fence_yello_0" geometry={nodes.polySurface1287_fence_yello_0.geometry} material={materials.fence_yello} />
          <mesh  castShadow receiveShadow name="polySurface1289_fence_columns_0" geometry={nodes.polySurface1289_fence_columns_0.geometry} material={materials.fence_columns} />
          <mesh  castShadow receiveShadow name="polySurface1290_fence_0" geometry={nodes.polySurface1290_fence_0.geometry} material={materials.fence} />
          <mesh  castShadow receiveShadow name="polySurface1290_fence_yello_0" geometry={nodes.polySurface1290_fence_yello_0.geometry} material={materials.fence_yello} />
          <mesh  castShadow receiveShadow name="polySurface1291_fence_columns_0" geometry={nodes.polySurface1291_fence_columns_0.geometry} material={materials.fence_columns} />
          <mesh  castShadow receiveShadow name="polySurface1428_fence_columns_0" geometry={nodes.polySurface1428_fence_columns_0.geometry} material={materials.fence_columns} />
          <mesh  castShadow receiveShadow name="polySurface1444_bushings_0" geometry={nodes.polySurface1444_bushings_0.geometry} material={materials.bushings} />
          <mesh  castShadow receiveShadow name="polySurface1446_bushings_0" geometry={nodes.polySurface1446_bushings_0.geometry} material={materials.bushings} />
        </mesh>
        <mesh  castShadow receiveShadow  
          name="screen" 
          geometry={nodes.screen.geometry} 
          
          position={[0.205, 0.281, -0.222]} rotation={[-0.037, 0.544, -3.117]} scale={[0.661, 0.679, 0.892]} >
            <meshBasicMaterial map={textureVSCode} toneMapped={true} forceSinglePass={true}/>
        </mesh>
        <motion.group  
          position={[0, 4, 10]}
          animate={{
            z: section === 1 ? 0 : -.8,
            y: section === 1 ? 0 : -.3,
          }}>
          <Float>
            <mesh  castShadow receiveShadow name="clouds" geometry={nodes.clouds.geometry} material={materials['mat21.001']} position={[0.42, 1.523, -1.039]} rotation={[0.229, 0.268, 0]} scale={3.11} />           
          </Float>      
        </motion.group>
        <mesh  castShadow receiveShadow name="island" geometry={nodes.island.geometry} material={materials.mat15}>
          <group name="group1019102024">
            <mesh  castShadow receiveShadow name="mesh1019102024" geometry={nodes.mesh1019102024.geometry} material={materials.mat20} />
            <mesh  castShadow receiveShadow name="mesh1019102024_1" geometry={nodes.mesh1019102024_1.geometry} material={materials.mat9} />
          </group>
          <group name="group1088612588" position={[0.171, 0, -1.204]}>
            <mesh  castShadow receiveShadow name="mesh1088612588" geometry={nodes.mesh1088612588.geometry} material={materials.mat18} />
            <mesh  castShadow receiveShadow name="mesh1088612588_1" geometry={nodes.mesh1088612588_1.geometry} material={materials.mat20} />
            <mesh  castShadow receiveShadow name="mesh1088612588_2" geometry={nodes.mesh1088612588_2.geometry} material={materials.mat19} />
          </group>
          <mesh  castShadow receiveShadow name="group1173642836" geometry={nodes.group1173642836.geometry} material={materials.mat15} position={[1.182, -0.385, 1.075]} scale={2.01} />
          <mesh  castShadow receiveShadow name="group1193226793" geometry={nodes.group1193226793.geometry} material={materials.mat9} />
          <mesh  castShadow receiveShadow name="group1211270279" geometry={nodes.group1211270279.geometry} material={materials.mat20} />
          <mesh  castShadow receiveShadow name="group1215832014" geometry={nodes.group1215832014.geometry} material={materials.mat15} />
          <group name="group137140296">
            <mesh  castShadow receiveShadow name="mesh137140296" geometry={nodes.mesh137140296.geometry} material={materials.mat19} />
            <mesh  castShadow receiveShadow name="mesh137140296_1" geometry={nodes.mesh137140296_1.geometry} material={materials.mat20} />
            <mesh  castShadow receiveShadow name="mesh137140296_2" geometry={nodes.mesh137140296_2.geometry} material={materials.mat18} />
          </group>
          <group name="group1434122196">
            <mesh  castShadow receiveShadow name="mesh1434122196" geometry={nodes.mesh1434122196.geometry} material={materials.mat9} />
            <mesh  castShadow receiveShadow name="mesh1434122196_1" geometry={nodes.mesh1434122196_1.geometry} material={materials.mat10} />
          </group>
          <group name="group1511101908">
            <mesh  castShadow receiveShadow name="mesh1511101908" geometry={nodes.mesh1511101908.geometry} material={materials.mat20} />
            <mesh  castShadow receiveShadow name="mesh1511101908_1" geometry={nodes.mesh1511101908_1.geometry} material={materials.mat9} />
          </group>
          <group name="group1511301575">
            <mesh  castShadow receiveShadow name="mesh1511301575" geometry={nodes.mesh1511301575.geometry} material={materials.mat10} />
            <mesh  castShadow receiveShadow name="mesh1511301575_1" geometry={nodes.mesh1511301575_1.geometry} material={materials.mat9} />
          </group>
          <group name="group1536715921" position={[0.542, -0.717, 0]}>
            <mesh  castShadow receiveShadow name="mesh1536715921" geometry={nodes.mesh1536715921.geometry} material={materials.mat18} />
            <mesh  castShadow receiveShadow name="mesh1536715921_1" geometry={nodes.mesh1536715921_1.geometry} material={materials.mat20} />
            <mesh  castShadow receiveShadow name="mesh1536715921_2" geometry={nodes.mesh1536715921_2.geometry} material={materials.mat19} />
          </group>
          <group name="group1555311382" scale={1.57}>
            <mesh  castShadow receiveShadow name="mesh1555311382" geometry={nodes.mesh1555311382.geometry} material={materials.mat20} />
            <mesh  castShadow receiveShadow name="mesh1555311382_1" geometry={nodes.mesh1555311382_1.geometry} material={materials.mat9} />
          </group>
          <group name="group1617223438">
            <mesh  castShadow receiveShadow name="mesh1617223438" geometry={nodes.mesh1617223438.geometry} material={materials.mat20} />
            <mesh  castShadow receiveShadow name="mesh1617223438_1" geometry={nodes.mesh1617223438_1.geometry} material={materials.mat9} />
          </group>
          <group name="group1623525114">
            <mesh  castShadow receiveShadow name="mesh1623525114" geometry={nodes.mesh1623525114.geometry} material={materials.mat9} />
            <mesh  castShadow receiveShadow name="mesh1623525114_1" geometry={nodes.mesh1623525114_1.geometry} material={materials.mat20} />
          </group>
          <group name="group1731338008">
            <mesh  castShadow receiveShadow name="mesh1731338008" geometry={nodes.mesh1731338008.geometry} material={materials.mat9} />
            <mesh  castShadow receiveShadow name="mesh1731338008_1" geometry={nodes.mesh1731338008_1.geometry} material={materials.mat20} />
          </group>
          <group name="group1736916870">
            <mesh  castShadow receiveShadow name="mesh1736916870" geometry={nodes.mesh1736916870.geometry} material={materials.mat20} />
            <mesh  castShadow receiveShadow name="mesh1736916870_1" geometry={nodes.mesh1736916870_1.geometry} material={materials.mat9} />
          </group>
          <mesh  castShadow receiveShadow name="group1762625985" geometry={nodes.group1762625985.geometry} material={materials.mat20} />
          <group name="group1774266040">
            <mesh  castShadow receiveShadow name="mesh1774266040" geometry={nodes.mesh1774266040.geometry} material={materials.mat15} />
            <mesh  castShadow receiveShadow name="mesh1774266040_1" geometry={nodes.mesh1774266040_1.geometry} material={materials.mat9} />
          </group>
          <group name="group1806860140">
            <mesh  castShadow receiveShadow name="mesh1806860140" geometry={nodes.mesh1806860140.geometry} material={materials.mat9} />
            <mesh  castShadow receiveShadow name="mesh1806860140_1" geometry={nodes.mesh1806860140_1.geometry} material={materials.mat15} />
            <mesh  castShadow receiveShadow name="mesh1806860140_2" geometry={nodes.mesh1806860140_2.geometry} material={materials.mat10} />
          </group>
          <mesh  castShadow receiveShadow name="group1910173211" geometry={nodes.group1910173211.geometry} material={materials.mat23} />
          <mesh  castShadow receiveShadow name="group1936711080" geometry={nodes.group1936711080.geometry} material={materials.mat15} />
          <mesh  castShadow receiveShadow name="group1950652135" geometry={nodes.group1950652135.geometry} material={materials.mat20} />
          <group name="group1987911788">
            <mesh  castShadow receiveShadow name="mesh1987911788" geometry={nodes.mesh1987911788.geometry} material={materials.mat9} />
            <mesh  castShadow receiveShadow name="mesh1987911788_1" geometry={nodes.mesh1987911788_1.geometry} material={materials.mat20} />
          </group>
          <mesh  castShadow receiveShadow name="group2016668438" geometry={nodes.group2016668438.geometry} material={materials.mat10} />
          <group name="group282285962">
            <mesh  castShadow receiveShadow name="mesh282285962" geometry={nodes.mesh282285962.geometry} material={materials.mat20} />
            <mesh  castShadow receiveShadow name="mesh282285962_1" geometry={nodes.mesh282285962_1.geometry} material={materials.mat9} />
          </group>
          <mesh  castShadow receiveShadow name="group414712452" geometry={nodes.group414712452.geometry} material={materials.mat15} />
          <mesh  castShadow receiveShadow name="group460129575" geometry={nodes.group460129575.geometry} material={materials.mat9} />
          <mesh  castShadow receiveShadow name="group468797730" geometry={nodes.group468797730.geometry} material={materials.mat9} position={[3.194, 0.704, -1.776]} rotation={[0, -0.885, 0]} scale={1.439} />
          <group name="group470834711">
            <mesh  castShadow receiveShadow name="mesh470834711" geometry={nodes.mesh470834711.geometry} material={materials.mat10} />
            <mesh  castShadow receiveShadow name="mesh470834711_1" geometry={nodes.mesh470834711_1.geometry} material={materials.mat9} />
          </group>
          <group name="group595478641">
            <mesh  castShadow receiveShadow name="mesh595478641" geometry={nodes.mesh595478641.geometry} material={materials.mat15} />
            <mesh  castShadow receiveShadow name="mesh595478641_1" geometry={nodes.mesh595478641_1.geometry} material={materials.mat9} />
          </group>
          <mesh  castShadow receiveShadow name="group611470674" geometry={nodes.group611470674.geometry} material={materials.mat20} />
          <group name="group624108358">
            <mesh  castShadow receiveShadow name="mesh624108358" geometry={nodes.mesh624108358.geometry} material={materials.mat10} />
            <mesh  castShadow receiveShadow name="mesh624108358_1" geometry={nodes.mesh624108358_1.geometry} material={materials.mat15} />
          </group>
          <group name="group632722702">
            <mesh  castShadow receiveShadow name="mesh632722702" geometry={nodes.mesh632722702.geometry} material={materials.mat15} />
            <mesh  castShadow receiveShadow name="mesh632722702_1" geometry={nodes.mesh632722702_1.geometry} material={materials.mat10} />
          </group>
          <group name="group643817545">
            <mesh  castShadow receiveShadow name="mesh643817545" geometry={nodes.mesh643817545.geometry} material={materials.mat20} />
            <mesh  castShadow receiveShadow name="mesh643817545_1" geometry={nodes.mesh643817545_1.geometry} material={materials.mat9} />
          </group>
          <group name="group663504923" position={[0.171, 0, -1.204]}>
            <mesh  castShadow receiveShadow name="mesh663504923" geometry={nodes.mesh663504923.geometry} material={materials.mat20} />
            <mesh  castShadow receiveShadow name="mesh663504923_1" geometry={nodes.mesh663504923_1.geometry} material={materials.mat19} />
            <mesh  castShadow receiveShadow name="mesh663504923_2" geometry={nodes.mesh663504923_2.geometry} material={materials.mat18} />
          </group>
          <mesh  castShadow receiveShadow name="group665622498" geometry={nodes.group665622498.geometry} material={materials.mat9} />
          <group name="group720648363">
            <mesh  castShadow receiveShadow name="mesh720648363" geometry={nodes.mesh720648363.geometry} material={materials.mat18} />
            <mesh  castShadow receiveShadow name="mesh720648363_1" geometry={nodes.mesh720648363_1.geometry} material={materials.mat20} />
            <mesh  castShadow receiveShadow name="mesh720648363_2" geometry={nodes.mesh720648363_2.geometry} material={materials.mat19} />
          </group>
          <group name="group811728704">
            <mesh  castShadow receiveShadow name="mesh811728704" geometry={nodes.mesh811728704.geometry} material={materials.mat9} />
            <mesh  castShadow receiveShadow name="mesh811728704_1" geometry={nodes.mesh811728704_1.geometry} material={materials.mat10} />
          </group>
          <group name="group897427996">
            <mesh  castShadow receiveShadow name="mesh897427996" geometry={nodes.mesh897427996.geometry} material={materials.mat9} />
            <mesh  castShadow receiveShadow name="mesh897427996_1" geometry={nodes.mesh897427996_1.geometry} material={materials.mat10} />
          </group>
          <group name="group947843091">
            <mesh  castShadow receiveShadow name="mesh947843091" geometry={nodes.mesh947843091.geometry} material={materials.mat9} />
            <mesh  castShadow receiveShadow name="mesh947843091_1" geometry={nodes.mesh947843091_1.geometry} material={materials.mat10} />
          </group>
          <group name="group954393760">
            <mesh  castShadow receiveShadow name="mesh954393760" geometry={nodes.mesh954393760.geometry} material={materials.mat9} />
            <mesh  castShadow receiveShadow name="mesh954393760_1" geometry={nodes.mesh954393760_1.geometry} material={materials.mat15} />
            <mesh  castShadow receiveShadow name="mesh954393760_2" geometry={nodes.mesh954393760_2.geometry} material={materials.mat10} />
          </group>
          <mesh  castShadow receiveShadow name="group962132412" geometry={nodes.group962132412.geometry} material={materials.mat23} />
          <group name="group972715649" position={[2.559, 0.449, 0.698]} rotation={[-0.069, 0.514, 0.035]}>
            <mesh  castShadow receiveShadow name="mesh972715649" geometry={nodes.mesh972715649.geometry} material={materials.mat21} />
            <mesh  castShadow receiveShadow name="mesh972715649_1" geometry={nodes.mesh972715649_1.geometry} material={materials.mat20} />
            <mesh  castShadow receiveShadow name="mesh972715649_2" geometry={nodes.mesh972715649_2.geometry} material={materials.mat19} />
            <mesh  castShadow receiveShadow name="mesh972715649_3" geometry={nodes.mesh972715649_3.geometry} material={materials.mat8} />
          </group>
          <group name="group981371949">
            <mesh  castShadow receiveShadow name="mesh981371949" geometry={nodes.mesh981371949.geometry} material={materials.mat9} />
            <mesh  castShadow receiveShadow name="mesh981371949_1" geometry={nodes.mesh981371949_1.geometry} material={materials.mat15} />
          </group>
          <group name="group99597693">
            <mesh  castShadow receiveShadow name="mesh99597693" geometry={nodes.mesh99597693.geometry} material={materials.mat20} />
            <mesh  castShadow receiveShadow name="mesh99597693_1" geometry={nodes.mesh99597693_1.geometry} material={materials.mat9} />
          </group>
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('models/office.glb')
