/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/Portatil.glb -K -k 
Author: Aullwen (https://sketchfab.com/Aullwen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-7d870e900889481395b4a575b9fa8c3e
Title: Laptop
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Portatil(props) {
  const { nodes, materials } = useGLTF('models/Portatil.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <mesh castShadow receiveShadow  name="Frame_ComputerFrame_0" geometry={nodes.Frame_ComputerFrame_0.geometry} material={materials.ComputerFrame} position={[0, 0.976, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh castShadow receiveShadow  name="Screen_ComputerScreen_0" geometry={nodes.Screen_ComputerScreen_0.geometry} material={materials.ComputerScreen} position={[0, 0.65, -10.3]} rotation={[Math.PI, 0, -Math.PI]} scale={[100, 100, 88.235]} />
      </group>
    </group>
  )
}

useGLTF.preload('models/Portatil.glb')
